services:
  postgres:
    image: postgres:17
    container_name: cartes-postgres-prod
    restart: always
    environment:
      POSTGRES_USER: cartes_app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cartes_prod
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    networks:
      - cartes-network

networks:
  cartes-network:
    driver: bridge

volumes:
  postgres-data-prod: